<?php

namespace App\Models;

use App\Builders\PropertyBuilder;
use App\Models\location\CityProvince;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Property extends Model
{
    use HasFactory;

    protected $fillable = ['thumbnail', 'name', 'province_id', 'district_id', 'commune_id', 'village_id', 'listing_type', 'category_id', 'price', 'bedroom', 'bathroom', 'floor', 'landsize', 'dimension', 'maplocation', 'description',];

    public function images()
    {
        return $this->hasMany(Image::class);
    }

    public function province()
    {
        return $this->belongsTo(CityProvince::class);
    }

    public static function query(): PropertyBuilder
    {
        return parent::query(); // TODO: Change the autogenerated stub
    }

    public function newEloquentBuilder($query): PropertyBuilder
    {
        return new PropertyBuilder($query);
    }


}
