<?php

namespace App\Models;

use App\Builders\PropertyBuilder;
use App\Models\location\CityProvince;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class
Property extends Model
{
    use HasFactory;


    protected $fillable = ['name', 'province_id', 'district_id', 'commune_id', 'village_id', 'listing_type', 'category_id', 'price', 'bedroom', 'bathroom', 'floor', 'landsize', 'dimension', 'maplocation', 'description','thumbnail','user_id'];


    public function images()
    {
        return $this->hasMany(Image::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function province()
    {
        return $this->belongsTo(CityProvince::class);
    }

    public static function query(): PropertyBuilder
    {
        return parent::query(); // TODO: Change the autogenerated stub
    }

    public function newEloquentBuilder($query): PropertyBuilder
    {
        return new PropertyBuilder($query);
    }


    protected static function booted()
    {
        if (request()->is('admin/*')) {
            if (auth()->check() && !auth()->user()->admin) {
                static::addGlobalScope('tenant', function (Builder $query) {
                    $query->where('user_id', auth()->id());
                });
            }
        }
    }

}
